language: cpp

compiler:
  - gcc
  - clang

before_install:
  - [ $TRAVIS_OS_NAME == linux ] && sudo apt-get update -qq
  - [ $TRAVIS_OS_NAME == linux ] && sudo apt-get install -qq libboost-all-dev libqt4-dev
  - [ $TRAVIS_OS_NAME == osx ] && brew update && brew install qt qwt

script: cmake . && make all

os:
  - linux
  - osx
