language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq libboost-all-dev libqt4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt qwt; fi

script: cmake . && make all

os:
  - linux
  - osx
