set(GSIM_MAJOR_VERSION 2)
set(GSIM_MINOR_VERSION 0)
set(GSIM_PATCH_LEVEL   1)
set(GSIM_VERSION       "2.0.1")
if (NOT DEFINED GSIM_INSTALL_PREFIX)
    set(GSIM_INSTALL_PREFIX  "/usr/local")
endif()
set(GSIM_QWT_AVAILABLE )
set(GSIM_ENVIRONMENT TRUE)

set(Qwt6_Qt4_LIBRARY )

# gsim
set(GSIM_CORE_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim.so.${GSIM_VERSION})
set(GSIM_QT_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim_qt.so.${GSIM_VERSION})
set(GSIM_QWT_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim_qwt.so.${GSIM_VERSION})

# gsim static libraries
set(GSIM_CORE_STATIC_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim.a)
set(GSIM_QT_STATIC_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim_qt.a)
set(GSIM_QWT_STATIC_LIBRARY 
    ${GSIM_INSTALL_PREFIX}/lib/libgsim_qwt.a)

include_directories(${GSIM_INSTALL_PREFIX}/include)
# For RPATH
link_directories(${GSIM_INSTALL_PREFIX}/lib)

find_package(Qt4 REQUIRED)
set(QT_USE_QTSCRIPT 1)
set(QT_USE_QTNETWORK 1)
set(QT_USE_QTSCRIPTTOOLS 1)
include(${QT_USE_FILE})

find_package(Boost 1.45.0)

if(NOT Boost_FOUND)
    message(FATAL_ERROR "Boost not found!")
else()
    include_directories(${Boost_INCLUDE_DIRS})
endif()

set(GSIM_REQUIRED_SHARED_LIBRARIES
    # Qt
    ${QT_LIBRARIES}
    # gsim
    ${GSIM_CORE_LIBRARY}
    ${GSIM_QT_LIBRARY})

set(GSIM_REQUIRED_STATIC_LIBRARIES
    # gsim
    ${GSIM_QT_STATIC_LIBRARY}
    ${GSIM_CORE_STATIC_LIBRARY}
    # Qt
    ${QT_LIBRARIES})

if(GSIM_QWT_AVAILABLE)
    list(APPEND GSIM_REQUIRED_SHARED_LIBRARIES 
        ${GSIM_QWT_LIBRARY} ${Qwt6_Qt4_LIBRARY})
    # list(APPEND GSIM_REQUIRED_STATIC_LIBRARIES ${GSIM_QWT_STATIC_LIBRARY})
endif()

if(DEFINED GSIM_STATIC_LINKING)
    set(GSIM_REQUIRED_LIBRARIES 
        ${GSIM_REQUIRED_STATIC_LIBRARIES})
else()
    set(GSIM_REQUIRED_LIBRARIES 
        ${GSIM_REQUIRED_SHARED_LIBRARIES})
endif()

